apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello2
  name: hello2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: network-multitool
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: hello2
  namespace: default
spec:
  ports:
    - name: web
      port: 80
    - name: https
      port: 443
  selector:
    app: hello2
