---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: prod
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: "init-sleep"
        image: "busybox:latest"
        imagePullPolicy: "IfNotPresent"
        command: ['sleep', '5']
      containers:
      - name: back
        image: mrgrav/some-test-backend:latest
        ports:
        - containerPort: 9000
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres:5432/news
