---
apiVersion: v1
kind: Service
metadata:
  name: front-back
  namespace: test
spec:
  ports:
    - name: web
      port: 80
    - name: api
      port: 9000
  selector:
    app: front-back
  type: ClusterIP